# Generated by Django 4.2.6 on 2023-10-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='sexo',
        ),
    ]
