# Generated by Django 4.2.6 on 2023-10-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_contato_sexo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
